##############################################################
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
##############################################################
# NodeJS __APP_NAME__ version __APP_VERSION__
#
# Run server with:
# docker run -d -p 80:8080 quay.io/legdba/__APP_NAME__:__APP_VERSION__
#
# To get the list of supported arguments run
# docker run -ti --rm -p 80:8080 quay.io/legdba/__APP_NAME__:__APP_VERSION__ --help
#
##############################################################
FROM legdba/javaw:jdk-8u51
MAINTAINER Vincent Bourdaraud <vincent@bourdaraud.com>

# Prepare for dir
RUN mkdir /opt/__APP_FULLNAME__

# Prepare for service
WORKDIR /opt/__APP_FULLNAME__
CMD ["-p", "8080"]
ENTRYPOINT [\
    "npm",\
    "start",\
    "--"\
    ]
EXPOSE 8080

# Add appl and tests that it is working fine
ADD __ARTIFACT__.tgz /opt/__APP_FULLNAME__/
COPY Dockerfile /opt/__APP_FULLNAME__/
RUN npm test && \
    npm start -- --help
