##############################################################
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
##############################################################
# Java __APP_FULLNAME__ service for testing purpose.
#
# Run server with:
# docker run -d -p 80:8080 quay.io/legdba/httpecho:[tag]
#
# To get the list of supported arguments run
# docker run -ti --rm -p 80:8080 quay.io/legdba/httpecho:[tag] --help
#
##############################################################
FROM legdba/javaw:jdk-8u51
MAINTAINER Vincent Bourdaraud <vincent@bourdaraud.com>

# Prepare for dir
RUN mkdir /opt/__APP_FULLNAME__

# Prepare for service
WORKDIR /opt/__APP_FULLNAME__
CMD ["-p", "8080"]
ENTRYPOINT [\
    "javaw",\
    "-XX:OnOutOfMemoryError=kill -9 %p",\
    "-Xms50m",\
    "-Xmx50m",\
    "-jar",\
    "/opt/__APP_FULLNAME__/__APP_FULLNAME__.jar"\
    ]
EXPOSE 8080

# Add Java App (copy one by one because of a bug on Docker 1.2-circleci on
# CircleCI causing multi-copy to skip some files and store them the wrong place)
ADD __APP_FULLNAME__.tgz /opt/__APP_FULLNAME__/
COPY Dockerfile /opt/__APP_FULLNAME__/
RUN javaw -jar __APP_FULLNAME__.jar --help
